//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 01:47:13 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://configuration.openempi.openhie.org/fileloadermap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openhie.openempi.configuration.xml.model;
